# Generated by Django 4.1.1 on 2022-11-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrtion',
            new_name='description',
        ),
    ]
