# Generated by Django 4.1.1 on 2022-11-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_descrtion_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('0 to 250', '0 TO 250'), ('250 TO 500', '250 TO 500'), ('500 TO 1000', '500 TO 1000'), ('1000 TO 2000', '1000 TO 2000')], max_length=65)),
            ],
        ),
    ]
