# Generated by Django 4.1.2 on 2022-11-20 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_color_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filterprice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.filter_price'),
        ),
    ]
