# Generated by Django 4.1.2 on 2022-11-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(unique=True, upload_to='product_image/'),
        ),
    ]
