# Generated by Django 4.1.2 on 2022-11-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_color_name_alter_filter_price_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
